<a href="https://colab.research.google.com/github/shivam-purve/Machine-learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [3]:
# list v/s numpy -time taken

from time import process_time

In [4]:
# time calculated for python_list to insert and modify the value
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0007101079999998205


In [7]:
# see time for numpy array
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5 # adds value 5 to all eleemnts to arrya
end_time = process_time()
print(end_time - start_time)

0.00017477300000035


# Numpy Arrays

In [8]:
# list
list1 = [i for i in range(1,6)]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [9]:
# Numpy Array
np_array = np.array([i for i in range(1,6)])
print(np_array)
type(np_array)


[1 2 3 4 5]


numpy.ndarray

In [11]:
# Creating one-D Numby Array
a = np.array([1,2,3,4,5])
print(a)
a.shape




[1 2 3 4 5]


(5,)

In [12]:
# Creating 2-D Array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [15]:
c = np.array([[1,2,3,4],[5,6,7,8]],dtype = float)
print(c)
c.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

# Placeholders in numpy array

In [16]:
# creating numpy array with all entries as zero
x = np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
# creating nupy array with all entries as 1
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# creating an array with one specific value
z = np.full((5,4),3)
print(z)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [20]:
# creating an identity matrix

a = np.eye(4) #identity matrix of 4x4 as identity matric always been acts as square matrix
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# creat a numpy array with random values

b = np.random.random((3,4))
print(b)

[[0.13675015 0.82679514 0.84679518 0.79571013]
 [0.07413561 0.10512524 0.09805614 0.92388791]
 [0.58446687 0.15785284 0.17284129 0.52752107]]


In [25]:
# random numpy array with rabdom between specified range as integer
c = np.random.randint(10,100,(3,5))
print(c)

[[20 28 12 92 12]
 [24 79 63 54 99]
 [94 62 91 34 36]]


In [26]:
# create random array with evenly spaced values specifying number of values needed
d = np.linspace(10,30,5)  # here 5 is size of array
print(d)

[10. 15. 20. 25. 30.]


In [27]:
# array of evenly spaced values specifying the step
e = np.arange(10,30,5)  # give random values from 10 to 30 having step size as 5
print(e)

[10 15 20 25]


In [28]:
# convert a list to numpy arrays
list_2 = [10,20,20,20,50]
np_array = np.asarray(list_2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

# analysing numpy arrays

In [29]:
c = np.random.randint(10,30,(5,5))
print(c)

[[20 11 14 13 24]
 [27 29 15 11 19]
 [17 27 25 22 12]
 [20 16 23 28 22]
 [18 16 25 17 18]]


In [30]:
print(c.shape)

(5, 5)


In [31]:
# printing dimension
print(c.ndim)

2


In [32]:
# printing number of elemnts
print(c.size)

25


In [33]:
# checking the data type of values in array
print(c.dtype)

int64


# Mathematical operation on numpy Arrays

In [35]:
list1 = [1,2,3,4]
list2 = [5,6,7,8,9,10]
print(list1 + list2) # actually this add list not an elements of respective list that concatenate just









[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [36]:
# adding numpy Arrays as their valuewise
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
# finding algebra of respective element on different numpy array
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[5 0 3]
 [8 7 5]
 [2 5 8]]
[[11 12 12]
 [10 15 17]
 [12 16 17]]
[[16 12 15]
 [18 22 22]
 [14 21 25]]
[[ -6 -12  -9]
 [ -2  -8 -12]
 [-10 -11  -9]]
[[ 55   0  36]
 [ 80 105  85]
 [ 24  80 136]]
[[0.45454545 0.         0.25      ]
 [0.8        0.46666667 0.29411765]
 [0.16666667 0.3125     0.47058824]]


In [37]:
# immplementing those operations with inbuilt fuctions
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[18 17 17]
 [13 13 28]
 [25 24 18]]
[[-14  -9  -9]
 [ -9 -13 -10]
 [-13 -14 -10]]
[[ 32  52  52]
 [ 22   0 171]
 [114  95  56]]
[[0.125      0.30769231 0.30769231]
 [0.18181818 0.         0.47368421]
 [0.31578947 0.26315789 0.28571429]]


In [38]:
# array manipuation
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[8 4 2]
 [2 8 1]]
(2, 3)
[[8 2]
 [4 8]
 [2 1]]
(3, 2)


In [39]:
#Another method to find transpose
trans2 = array.T # will find transpose
print(trans2)
print(trans2.shape)

[[8 2]
 [4 8]
 [2 1]]
(3, 2)


In [40]:
# numpy array reshaping

a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 6 9]
 [9 8 5]]
(2, 3)


In [41]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 6]
 [9 9]
 [8 5]]
(3, 2)
